use_frameworks!

platform :ios, '12.1'

target 'AiLevelTestKit_Example' do
  pod 'AiLevelTestKit', :path => '../'

  target 'AiLevelTestKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
